version: '3.8'

services:
  api:
    build: .
    container_name: customer-segmentation-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    # remove depends_on since we don't need local MongoDB
    # depends_on:
    #   - mongo

  frontend:
    build: ./frontend
    container_name: customer-segmentation-frontend
    ports:
      - "3000:80"
    depends_on:
      - api

# We no longer need local MongoDB since we're using Atlas:
# mongo:
#   image: mongo:6.0
#   container_name: customer-segmentation-mongo
#   ports:
#     - "27017:27017"
#   volumes:
#     - mongo_data:/data/db

# volumes:
#   mongo_data:
